// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backup} from '../models';
import {config} from '../models';
import {backend} from '../models';
import {browser} from '../models';
import {proxy} from '../models';
import {cdp} from '../models';
import {logger} from '../models';
import {launchcode} from '../models';
import {usernamescan} from '../models';

export function BackupExportPackage():Promise<Record<string, any>>;

export function BackupGetManifestTemplate():Promise<backup.Manifest>;

export function BackupGetScopeDefinition():Promise<backup.Scope>;

export function BackupImportPackage(arg1:boolean):Promise<Record<string, any>>;

export function BackupInitializeSystem():Promise<Record<string, any>>;

export function BookmarkList():Promise<Array<config.BrowserBookmark>>;

export function BookmarkReset():Promise<void>;

export function BookmarkSave(arg1:Array<config.BrowserBookmark>):Promise<void>;

export function BrowserAccountBatchLinkProfiles(arg1:Array<string>,arg2:Array<string>):Promise<Record<string, string>>;

export function BrowserAccountBatchUnlinkProfiles(arg1:Array<string>,arg2:Array<string>):Promise<Record<string, string>>;

export function BrowserAccountCreate(arg1:backend.BrowserAccountInput):Promise<backend.BrowserAccount>;

export function BrowserAccountDelete(arg1:string):Promise<void>;

export function BrowserAccountExport(arg1:Array<string>,arg2:boolean):Promise<string>;

export function BrowserAccountGet(arg1:string):Promise<backend.BrowserAccount>;

export function BrowserAccountImport(arg1:string):Promise<number>;

export function BrowserAccountList():Promise<Array<backend.BrowserAccount>>;

export function BrowserAccountRestoreCookiesToProfile(arg1:string,arg2:string,arg3:boolean):Promise<number>;

export function BrowserAccountSaveCookiesFromProfile(arg1:string,arg2:string):Promise<number>;

export function BrowserAccountSetProfiles(arg1:string,arg2:Array<string>):Promise<void>;

export function BrowserAccountUnlinkProfile(arg1:string,arg2:string):Promise<void>;

export function BrowserAccountUpdate(arg1:string,arg2:backend.BrowserAccountInput):Promise<backend.BrowserAccount>;

export function BrowserClearCookies(arg1:string):Promise<void>;

export function BrowserCoreDelete(arg1:string):Promise<void>;

export function BrowserCoreDownload(arg1:string,arg2:string,arg3:string):Promise<void>;

export function BrowserCoreExtendedInfo():Promise<Array<browser.CoreExtendedInfo>>;

export function BrowserCoreList():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSave(arg1:browser.CoreInput):Promise<void>;

export function BrowserCoreScan():Promise<Array<config.BrowserCore>>;

export function BrowserCoreSetDefault(arg1:string):Promise<void>;

export function BrowserCoreValidate(arg1:string):Promise<browser.CoreValidateResult>;

export function BrowserExportCookies(arg1:string):Promise<string>;

export function BrowserExtensionCreate(arg1:backend.BrowserExtensionInput):Promise<backend.BrowserExtension>;

export function BrowserExtensionDelete(arg1:string):Promise<void>;

export function BrowserExtensionGet(arg1:string):Promise<backend.BrowserExtension>;

export function BrowserExtensionList():Promise<Array<backend.BrowserExtension>>;

export function BrowserExtensionSetProfiles(arg1:string,arg2:Array<string>):Promise<void>;

export function BrowserExtensionToggle(arg1:string,arg2:boolean):Promise<void>;

export function BrowserExtensionUpdate(arg1:string,arg2:backend.BrowserExtensionInput):Promise<backend.BrowserExtension>;

export function BrowserExtensionValidatePath(arg1:string):Promise<backend.ExtensionValidateResult>;

export function BrowserGetAllTags():Promise<Array<string>>;

export function BrowserGetCookies(arg1:string):Promise<Array<backend.CookieInfo>>;

export function BrowserInstanceGetTabs(arg1:string):Promise<Array<browser.Tab>>;

export function BrowserInstanceOpenUrl(arg1:string,arg2:string):Promise<boolean>;

export function BrowserInstanceRestart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStart(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartByCode(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStartWithParams(arg1:string,arg2:Array<string>,arg3:Array<string>,arg4:boolean):Promise<browser.Profile>;

export function BrowserInstanceStatus(arg1:string):Promise<browser.Profile>;

export function BrowserInstanceStop(arg1:string):Promise<browser.Profile>;

export function BrowserProfileBatchRemoveTags(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function BrowserProfileBatchSetTags(arg1:Array<string>,arg2:Array<string>,arg3:boolean):Promise<void>;

export function BrowserProfileCopy(arg1:string,arg2:string):Promise<browser.Profile>;

export function BrowserProfileCreate(arg1:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProfileDelete(arg1:string):Promise<void>;

export function BrowserProfileGetCode(arg1:string):Promise<string>;

export function BrowserProfileList():Promise<Array<browser.Profile>>;

export function BrowserProfileListByTag(arg1:string):Promise<Array<browser.Profile>>;

export function BrowserProfileRegenerateCode(arg1:string):Promise<string>;

export function BrowserProfileSetCode(arg1:string,arg2:string):Promise<string>;

export function BrowserProfileSetKeywords(arg1:string,arg2:Array<string>):Promise<browser.Profile>;

export function BrowserProfileUpdate(arg1:string,arg2:browser.ProfileInput):Promise<browser.Profile>;

export function BrowserProxyBatchCheckIPHealth(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyIPHealthResult>>;

export function BrowserProxyBatchTestSpeed(arg1:Array<string>,arg2:number):Promise<Array<backend.ProxyTestResult>>;

export function BrowserProxyCancelBatch():Promise<void>;

export function BrowserProxyCheckIPHealth(arg1:string):Promise<backend.ProxyIPHealthResult>;

export function BrowserProxyDetectIPByConfig(arg1:string,arg2:string):Promise<proxy.IPDetectResult>;

export function BrowserProxyDetectLocalIP(arg1:string):Promise<proxy.IPDetectResult>;

export function BrowserProxyFetchClashByURL(arg1:string):Promise<Record<string, any>>;

export function BrowserProxyList():Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListByGroup(arg1:string):Promise<Array<config.BrowserProxy>>;

export function BrowserProxyListGroups():Promise<Array<string>>;

export function BrowserProxyListIPDetectSources():Promise<Array<proxy.IPDetectSource>>;

export function BrowserProxyProbeProtocol(arg1:string):Promise<proxy.ProbeResult>;

export function BrowserProxySourceDelete(arg1:string,arg2:boolean):Promise<void>;

export function BrowserProxySourceList():Promise<Array<browser.ProxySource>>;

export function BrowserProxySourceListOverrides(arg1:string):Promise<Array<browser.ProxySourceOverride>>;

export function BrowserProxySourceRefresh(arg1:string):Promise<void>;

export function BrowserProxySourceRefreshAll():Promise<void>;

export function BrowserProxySourceRemoveOverride(arg1:string,arg2:string):Promise<void>;

export function BrowserProxySourceSetOverride(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function BrowserProxySourceUpsert(arg1:browser.ProxySource):Promise<browser.ProxySource>;

export function BrowserProxyTestSpeed(arg1:string):Promise<backend.ProxyTestResult>;

export function BrowserRenameTag(arg1:string,arg2:string):Promise<void>;

export function BrowserSetCookies(arg1:string,arg2:Array<backend.CookieInfo>):Promise<void>;

export function BrowserSnapshotCreate(arg1:string,arg2:string):Promise<backend.SnapshotInfo>;

export function BrowserSnapshotDelete(arg1:string,arg2:string):Promise<void>;

export function BrowserSnapshotList(arg1:string):Promise<Array<backend.SnapshotInfo>>;

export function BrowserSnapshotRestore(arg1:string,arg2:string):Promise<void>;

export function CDPAddInterceptRule(arg1:string,arg2:cdp.InterceptRule):Promise<void>;

export function CDPCaptureScreenshot(arg1:string):Promise<string>;

export function CDPClearAllCookies(arg1:string):Promise<void>;

export function CDPClearAllCookiesAuth(arg1:string,arg2:string):Promise<void>;

export function CDPClearConsoleLogs(arg1:string):Promise<void>;

export function CDPClearNetworkRequests(arg1:string):Promise<void>;

export function CDPClearWebSocketMessages(arg1:string):Promise<void>;

export function CDPDeleteCookie(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function CDPDisableIntercept(arg1:string):Promise<void>;

export function CDPEnableConsoleCapture(arg1:string):Promise<void>;

export function CDPEnableIntercept(arg1:string):Promise<void>;

export function CDPExecuteJavaScript(arg1:string,arg2:string):Promise<string>;

export function CDPExecuteJavaScriptAuth(arg1:string,arg2:string,arg3:string):Promise<string>;

export function CDPExportHAR(arg1:string):Promise<string>;

export function CDPGetConsoleLogs(arg1:string):Promise<Array<cdp.ConsoleLog>>;

export function CDPGetConsoleLogsAuth(arg1:string,arg2:string):Promise<Array<cdp.ConsoleLog>>;

export function CDPGetCookies(arg1:string):Promise<Array<cdp.Cookie>>;

export function CDPGetCookiesAuth(arg1:string,arg2:string):Promise<Array<cdp.Cookie>>;

export function CDPGetInterceptRules(arg1:string):Promise<Array<cdp.InterceptRule>>;

export function CDPGetNetworkRequests(arg1:string):Promise<Array<cdp.NetworkRequest>>;

export function CDPGetNetworkRequestsAuth(arg1:string,arg2:string):Promise<Array<cdp.NetworkRequest>>;

export function CDPGetStatistics(arg1:string):Promise<Record<string, any>>;

export function CDPGetStorage(arg1:string,arg2:string):Promise<Record<string, string>>;

export function CDPGetWebSocketMessages(arg1:string):Promise<Array<cdp.WebSocketMessage>>;

export function CDPListSessions():Promise<Array<string>>;

export function CDPReloadPage(arg1:string):Promise<void>;

export function CDPRemoveInterceptRule(arg1:string,arg2:string):Promise<void>;

export function CDPSessionClose(arg1:string):Promise<void>;

export function CDPSessionCreate(arg1:string,arg2:string):Promise<string>;

export function CDPSetCookie(arg1:string,arg2:cdp.Cookie):Promise<void>;

export function CDPSetCookieAuth(arg1:string,arg2:string,arg3:cdp.Cookie):Promise<void>;

export function CDPUpdateInterceptRule(arg1:string,arg2:cdp.InterceptRule):Promise<void>;

export function ClearAppLogs():Promise<void>;

export function CreateGroup(arg1:browser.GroupInput):Promise<browser.Group>;

export function CreateProfile(arg1:browser.ProfileInput):Promise<browser.Profile>;

export function CreateTemplate(arg1:browser.TemplateInput):Promise<browser.Template>;

export function DeleteGroup(arg1:string):Promise<void>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DeleteTemplate(arg1:string):Promise<void>;

export function FetchRemoteAuthorProfile(arg1:string,arg2:number):Promise<Record<string, any>>;

export function ForceQuit():Promise<void>;

export function GenerateCDKeys(arg1:number):Promise<Array<string>>;

export function GetActivityLog():Promise<Array<backend.ActivityEntry>>;

export function GetAppConfig():Promise<Record<string, any>>;

export function GetAppLogs():Promise<Array<logger.MemoryLogEntry>>;

export function GetBrowserSettings():Promise<browser.Settings>;

export function GetDashboardMetrics():Promise<backend.DashboardMetrics>;

export function GetDashboardStats():Promise<Record<string, any>>;

export function GetInterceptor():Promise<logger.MethodInterceptor>;

export function GetLaunchServerInfo():Promise<Record<string, any>>;

export function GetLicenseStatus():Promise<backend.LicenseStatus>;

export function GetLogLevel():Promise<string>;

export function GetMemoryStats():Promise<Record<string, any>>;

export function GetRecentErrors():Promise<Array<backend.ActivityEntry>>;

export function GetRunningInstances():Promise<Array<browser.Profile>>;

export function ListGroups():Promise<Array<browser.GroupWithCount>>;

export function ListTemplates():Promise<Array<browser.Template>>;

export function MoveInstancesToGroup(arg1:Array<string>,arg2:string):Promise<void>;

export function OpenCorePath(arg1:string):Promise<void>;

export function OpenUserDataDir(arg1:string):Promise<void>;

export function QuitAppOnly():Promise<void>;

export function RedeemCDKey(arg1:string):Promise<void>;

export function RedeemGithubStar():Promise<void>;

export function ReloadConfig():Promise<void>;

export function SaveBrowserProxies(arg1:Array<config.BrowserProxy>):Promise<void>;

export function SaveBrowserSettings(arg1:browser.Settings):Promise<void>;

export function ScanLocalProxy():Promise<proxy.LocalProxyScanResult>;

export function SetLogLevel(arg1:string):Promise<void>;

export function StartInstance(arg1:string):Promise<browser.Profile>;

export function StartInstanceWithParams(arg1:string,arg2:launchcode.LaunchRequestParams):Promise<browser.Profile>;

export function StopInstance(arg1:string):Promise<void>;

export function TestProxyConnectivity(arg1:string,arg2:string):Promise<backend.ProxyTestResult>;

export function TestProxyRealConnectivity(arg1:string):Promise<backend.ProxyTestResult>;

export function TriggerGC():Promise<void>;

export function UpdateGroup(arg1:string,arg2:browser.GroupInput):Promise<browser.Group>;

export function UpdateProfile(arg1:string,arg2:browser.ProfileInput):Promise<browser.Profile>;

export function UpdateTemplate(arg1:string,arg2:browser.TemplateInput):Promise<browser.Template>;

export function UsernameScanGenerate(arg1:usernamescan.GeneratorOptions):Promise<Array<string>>;

export function UsernameScanPause():Promise<usernamescan.Snapshot>;

export function UsernameScanSnapshot():Promise<usernamescan.Snapshot>;

export function UsernameScanStart(arg1:usernamescan.StartRequest):Promise<usernamescan.Snapshot>;

export function UsernameScanStop():Promise<usernamescan.Snapshot>;

export function ValidateProxyConfig(arg1:string,arg2:string):Promise<backend.ProxyValidationResult>;
