// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupExportPackage() {
  return window['go']['main']['App']['BackupExportPackage']();
}

export function BackupGetManifestTemplate() {
  return window['go']['main']['App']['BackupGetManifestTemplate']();
}

export function BackupGetScopeDefinition() {
  return window['go']['main']['App']['BackupGetScopeDefinition']();
}

export function BackupImportPackage(arg1) {
  return window['go']['main']['App']['BackupImportPackage'](arg1);
}

export function BackupInitializeSystem() {
  return window['go']['main']['App']['BackupInitializeSystem']();
}

export function BookmarkList() {
  return window['go']['main']['App']['BookmarkList']();
}

export function BookmarkReset() {
  return window['go']['main']['App']['BookmarkReset']();
}

export function BookmarkSave(arg1) {
  return window['go']['main']['App']['BookmarkSave'](arg1);
}

export function BrowserAccountCreate(arg1) {
  return window['go']['main']['App']['BrowserAccountCreate'](arg1);
}

export function BrowserAccountDelete(arg1) {
  return window['go']['main']['App']['BrowserAccountDelete'](arg1);
}

export function BrowserAccountExport(arg1, arg2) {
  return window['go']['main']['App']['BrowserAccountExport'](arg1, arg2);
}

export function BrowserAccountGet(arg1) {
  return window['go']['main']['App']['BrowserAccountGet'](arg1);
}

export function BrowserAccountImport(arg1) {
  return window['go']['main']['App']['BrowserAccountImport'](arg1);
}

export function BrowserAccountList() {
  return window['go']['main']['App']['BrowserAccountList']();
}

export function BrowserAccountRestoreCookiesToProfile(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserAccountRestoreCookiesToProfile'](arg1, arg2, arg3);
}

export function BrowserAccountSaveCookiesFromProfile(arg1, arg2) {
  return window['go']['main']['App']['BrowserAccountSaveCookiesFromProfile'](arg1, arg2);
}

export function BrowserAccountSetProfiles(arg1, arg2) {
  return window['go']['main']['App']['BrowserAccountSetProfiles'](arg1, arg2);
}

export function BrowserAccountUpdate(arg1, arg2) {
  return window['go']['main']['App']['BrowserAccountUpdate'](arg1, arg2);
}

export function BrowserClearCookies(arg1) {
  return window['go']['main']['App']['BrowserClearCookies'](arg1);
}

export function BrowserCoreDelete(arg1) {
  return window['go']['main']['App']['BrowserCoreDelete'](arg1);
}

export function BrowserCoreDownload(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserCoreDownload'](arg1, arg2, arg3);
}

export function BrowserCoreExtendedInfo() {
  return window['go']['main']['App']['BrowserCoreExtendedInfo']();
}

export function BrowserCoreList() {
  return window['go']['main']['App']['BrowserCoreList']();
}

export function BrowserCoreSave(arg1) {
  return window['go']['main']['App']['BrowserCoreSave'](arg1);
}

export function BrowserCoreScan() {
  return window['go']['main']['App']['BrowserCoreScan']();
}

export function BrowserCoreSetDefault(arg1) {
  return window['go']['main']['App']['BrowserCoreSetDefault'](arg1);
}

export function BrowserCoreValidate(arg1) {
  return window['go']['main']['App']['BrowserCoreValidate'](arg1);
}

export function BrowserExportCookies(arg1) {
  return window['go']['main']['App']['BrowserExportCookies'](arg1);
}

export function BrowserExtensionCreate(arg1) {
  return window['go']['main']['App']['BrowserExtensionCreate'](arg1);
}

export function BrowserExtensionDelete(arg1) {
  return window['go']['main']['App']['BrowserExtensionDelete'](arg1);
}

export function BrowserExtensionGet(arg1) {
  return window['go']['main']['App']['BrowserExtensionGet'](arg1);
}

export function BrowserExtensionList() {
  return window['go']['main']['App']['BrowserExtensionList']();
}

export function BrowserExtensionSetProfiles(arg1, arg2) {
  return window['go']['main']['App']['BrowserExtensionSetProfiles'](arg1, arg2);
}

export function BrowserExtensionToggle(arg1, arg2) {
  return window['go']['main']['App']['BrowserExtensionToggle'](arg1, arg2);
}

export function BrowserExtensionUpdate(arg1, arg2) {
  return window['go']['main']['App']['BrowserExtensionUpdate'](arg1, arg2);
}

export function BrowserExtensionValidatePath(arg1) {
  return window['go']['main']['App']['BrowserExtensionValidatePath'](arg1);
}

export function BrowserGetAllTags() {
  return window['go']['main']['App']['BrowserGetAllTags']();
}

export function BrowserGetCookies(arg1) {
  return window['go']['main']['App']['BrowserGetCookies'](arg1);
}

export function BrowserInstanceGetTabs(arg1) {
  return window['go']['main']['App']['BrowserInstanceGetTabs'](arg1);
}

export function BrowserInstanceOpenUrl(arg1, arg2) {
  return window['go']['main']['App']['BrowserInstanceOpenUrl'](arg1, arg2);
}

export function BrowserInstanceRestart(arg1) {
  return window['go']['main']['App']['BrowserInstanceRestart'](arg1);
}

export function BrowserInstanceStart(arg1) {
  return window['go']['main']['App']['BrowserInstanceStart'](arg1);
}

export function BrowserInstanceStartByCode(arg1) {
  return window['go']['main']['App']['BrowserInstanceStartByCode'](arg1);
}

export function BrowserInstanceStartWithParams(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserInstanceStartWithParams'](arg1, arg2, arg3, arg4);
}

export function BrowserInstanceStatus(arg1) {
  return window['go']['main']['App']['BrowserInstanceStatus'](arg1);
}

export function BrowserInstanceStop(arg1) {
  return window['go']['main']['App']['BrowserInstanceStop'](arg1);
}

export function BrowserProfileBatchRemoveTags(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileBatchRemoveTags'](arg1, arg2);
}

export function BrowserProfileBatchSetTags(arg1, arg2, arg3) {
  return window['go']['main']['App']['BrowserProfileBatchSetTags'](arg1, arg2, arg3);
}

export function BrowserProfileCopy(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileCopy'](arg1, arg2);
}

export function BrowserProfileCreate(arg1) {
  return window['go']['main']['App']['BrowserProfileCreate'](arg1);
}

export function BrowserProfileDelete(arg1) {
  return window['go']['main']['App']['BrowserProfileDelete'](arg1);
}

export function BrowserProfileGetCode(arg1) {
  return window['go']['main']['App']['BrowserProfileGetCode'](arg1);
}

export function BrowserProfileList() {
  return window['go']['main']['App']['BrowserProfileList']();
}

export function BrowserProfileListByTag(arg1) {
  return window['go']['main']['App']['BrowserProfileListByTag'](arg1);
}

export function BrowserProfileRegenerateCode(arg1) {
  return window['go']['main']['App']['BrowserProfileRegenerateCode'](arg1);
}

export function BrowserProfileSetCode(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetCode'](arg1, arg2);
}

export function BrowserProfileSetKeywords(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileSetKeywords'](arg1, arg2);
}

export function BrowserProfileUpdate(arg1, arg2) {
  return window['go']['main']['App']['BrowserProfileUpdate'](arg1, arg2);
}

export function BrowserProxyBatchCheckIPHealth(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchCheckIPHealth'](arg1, arg2);
}

export function BrowserProxyBatchTestSpeed(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxyBatchTestSpeed'](arg1, arg2);
}

export function BrowserProxyCancelBatch() {
  return window['go']['main']['App']['BrowserProxyCancelBatch']();
}

export function BrowserProxyCheckIPHealth(arg1) {
  return window['go']['main']['App']['BrowserProxyCheckIPHealth'](arg1);
}

export function BrowserProxyFetchClashByURL(arg1) {
  return window['go']['main']['App']['BrowserProxyFetchClashByURL'](arg1);
}

export function BrowserProxyList() {
  return window['go']['main']['App']['BrowserProxyList']();
}

export function BrowserProxyListByGroup(arg1) {
  return window['go']['main']['App']['BrowserProxyListByGroup'](arg1);
}

export function BrowserProxyListGroups() {
  return window['go']['main']['App']['BrowserProxyListGroups']();
}

export function BrowserProxySourceDelete(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxySourceDelete'](arg1, arg2);
}

export function BrowserProxySourceList() {
  return window['go']['main']['App']['BrowserProxySourceList']();
}

export function BrowserProxySourceListOverrides(arg1) {
  return window['go']['main']['App']['BrowserProxySourceListOverrides'](arg1);
}

export function BrowserProxySourceRefresh(arg1) {
  return window['go']['main']['App']['BrowserProxySourceRefresh'](arg1);
}

export function BrowserProxySourceRefreshAll() {
  return window['go']['main']['App']['BrowserProxySourceRefreshAll']();
}

export function BrowserProxySourceRemoveOverride(arg1, arg2) {
  return window['go']['main']['App']['BrowserProxySourceRemoveOverride'](arg1, arg2);
}

export function BrowserProxySourceSetOverride(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['BrowserProxySourceSetOverride'](arg1, arg2, arg3, arg4);
}

export function BrowserProxySourceUpsert(arg1) {
  return window['go']['main']['App']['BrowserProxySourceUpsert'](arg1);
}

export function BrowserProxyTestSpeed(arg1) {
  return window['go']['main']['App']['BrowserProxyTestSpeed'](arg1);
}

export function BrowserRenameTag(arg1, arg2) {
  return window['go']['main']['App']['BrowserRenameTag'](arg1, arg2);
}

export function BrowserSetCookies(arg1, arg2) {
  return window['go']['main']['App']['BrowserSetCookies'](arg1, arg2);
}

export function BrowserSnapshotCreate(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotCreate'](arg1, arg2);
}

export function BrowserSnapshotDelete(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotDelete'](arg1, arg2);
}

export function BrowserSnapshotList(arg1) {
  return window['go']['main']['App']['BrowserSnapshotList'](arg1);
}

export function BrowserSnapshotRestore(arg1, arg2) {
  return window['go']['main']['App']['BrowserSnapshotRestore'](arg1, arg2);
}

export function CDPCaptureScreenshot(arg1) {
  return window['go']['main']['App']['CDPCaptureScreenshot'](arg1);
}

export function CDPClearConsoleLogs(arg1) {
  return window['go']['main']['App']['CDPClearConsoleLogs'](arg1);
}

export function CDPClearNetworkRequests(arg1) {
  return window['go']['main']['App']['CDPClearNetworkRequests'](arg1);
}

export function CDPExecuteJavaScript(arg1, arg2) {
  return window['go']['main']['App']['CDPExecuteJavaScript'](arg1, arg2);
}

export function CDPExportHAR(arg1) {
  return window['go']['main']['App']['CDPExportHAR'](arg1);
}

export function CDPGetConsoleLogs(arg1) {
  return window['go']['main']['App']['CDPGetConsoleLogs'](arg1);
}

export function CDPGetNetworkRequests(arg1) {
  return window['go']['main']['App']['CDPGetNetworkRequests'](arg1);
}

export function CDPGetStatistics(arg1) {
  return window['go']['main']['App']['CDPGetStatistics'](arg1);
}

export function CDPGetStorage(arg1, arg2) {
  return window['go']['main']['App']['CDPGetStorage'](arg1, arg2);
}

export function CDPListSessions() {
  return window['go']['main']['App']['CDPListSessions']();
}

export function CDPSessionClose(arg1) {
  return window['go']['main']['App']['CDPSessionClose'](arg1);
}

export function CDPSessionCreate(arg1, arg2) {
  return window['go']['main']['App']['CDPSessionCreate'](arg1, arg2);
}

export function ClearAppLogs() {
  return window['go']['main']['App']['ClearAppLogs']();
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function FetchRemoteAuthorProfile(arg1, arg2) {
  return window['go']['main']['App']['FetchRemoteAuthorProfile'](arg1, arg2);
}

export function ForceQuit() {
  return window['go']['main']['App']['ForceQuit']();
}

export function GenerateCDKeys(arg1) {
  return window['go']['main']['App']['GenerateCDKeys'](arg1);
}

export function GetActivityLog() {
  return window['go']['main']['App']['GetActivityLog']();
}

export function GetAppConfig() {
  return window['go']['main']['App']['GetAppConfig']();
}

export function GetAppLogs() {
  return window['go']['main']['App']['GetAppLogs']();
}

export function GetBrowserSettings() {
  return window['go']['main']['App']['GetBrowserSettings']();
}

export function GetDashboardMetrics() {
  return window['go']['main']['App']['GetDashboardMetrics']();
}

export function GetDashboardStats() {
  return window['go']['main']['App']['GetDashboardStats']();
}

export function GetInterceptor() {
  return window['go']['main']['App']['GetInterceptor']();
}

export function GetLaunchServerInfo() {
  return window['go']['main']['App']['GetLaunchServerInfo']();
}

export function GetLicenseStatus() {
  return window['go']['main']['App']['GetLicenseStatus']();
}

export function GetLogLevel() {
  return window['go']['main']['App']['GetLogLevel']();
}

export function GetMemoryStats() {
  return window['go']['main']['App']['GetMemoryStats']();
}

export function GetRecentErrors() {
  return window['go']['main']['App']['GetRecentErrors']();
}

export function GetRunningInstances() {
  return window['go']['main']['App']['GetRunningInstances']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function MoveInstancesToGroup(arg1, arg2) {
  return window['go']['main']['App']['MoveInstancesToGroup'](arg1, arg2);
}

export function OpenCorePath(arg1) {
  return window['go']['main']['App']['OpenCorePath'](arg1);
}

export function OpenUserDataDir(arg1) {
  return window['go']['main']['App']['OpenUserDataDir'](arg1);
}

export function QuitAppOnly() {
  return window['go']['main']['App']['QuitAppOnly']();
}

export function RedeemCDKey(arg1) {
  return window['go']['main']['App']['RedeemCDKey'](arg1);
}

export function RedeemGithubStar() {
  return window['go']['main']['App']['RedeemGithubStar']();
}

export function ReloadConfig() {
  return window['go']['main']['App']['ReloadConfig']();
}

export function SaveBrowserProxies(arg1) {
  return window['go']['main']['App']['SaveBrowserProxies'](arg1);
}

export function SaveBrowserSettings(arg1) {
  return window['go']['main']['App']['SaveBrowserSettings'](arg1);
}

export function SetLogLevel(arg1) {
  return window['go']['main']['App']['SetLogLevel'](arg1);
}

export function StartInstance(arg1) {
  return window['go']['main']['App']['StartInstance'](arg1);
}

export function StartInstanceWithParams(arg1, arg2) {
  return window['go']['main']['App']['StartInstanceWithParams'](arg1, arg2);
}

export function TestProxyConnectivity(arg1, arg2) {
  return window['go']['main']['App']['TestProxyConnectivity'](arg1, arg2);
}

export function TestProxyRealConnectivity(arg1) {
  return window['go']['main']['App']['TestProxyRealConnectivity'](arg1);
}

export function TriggerGC() {
  return window['go']['main']['App']['TriggerGC']();
}

export function UpdateGroup(arg1, arg2) {
  return window['go']['main']['App']['UpdateGroup'](arg1, arg2);
}

export function UsernameScanGenerate(arg1) {
  return window['go']['main']['App']['UsernameScanGenerate'](arg1);
}

export function UsernameScanPause() {
  return window['go']['main']['App']['UsernameScanPause']();
}

export function UsernameScanSnapshot() {
  return window['go']['main']['App']['UsernameScanSnapshot']();
}

export function UsernameScanStart(arg1) {
  return window['go']['main']['App']['UsernameScanStart'](arg1);
}

export function UsernameScanStop() {
  return window['go']['main']['App']['UsernameScanStop']();
}

export function ValidateProxyConfig(arg1, arg2) {
  return window['go']['main']['App']['ValidateProxyConfig'](arg1, arg2);
}
